#!/bin/dash

if test "$#" -ne 4
then
    echo "usage: give-add <assignment> <solution> <autotests> <automarking>" >&2
    exit 1
fi

if test ! -e '.give'
then
    mkdir '.give' &&
    echo "directory .give created"
fi

if ! echo "$1" | grep -E '^[a-z][a-zA-Z0-9_]*$' >/dev/null
then
    echo "give-add: invalid assignment: ${1}" >&2
    exit 1
fi

if ! echo "$2" | grep -E '^[a-zA-Z0-9_\-\/\.]*$' >/dev/null
then
    echo "give-add: invalid solution: ${2}" >&2
    exit 1
fi

if test ! -e "$2"
then
    echo "give-add: $2: No such file or directory" >&2
    exit 1
fi

if test ! -e "$3"
then
    echo "give-add: $3: No such file or directory" >&2
    exit 1
fi

if test ! -e "$4"
then
    echo "give-add: $4: No such file or directory" >&2
    exit 1
fi

cd .give &&
if test -e "$1"
then
    echo "give-add: assignment ${1} already exists" >&2
    exit 1
fi

cd .. &&
mkdir ".give/${1}" && 
cp "$2" ".give/${1}" &&
mv ".give/${1}/${2}" ".give/${1}/_solution" &&
cp "$3" ".give/${1}" &&
mv ".give/${1}/${3}" ".give/${1}/_AUTOTESTS" &&
cp "$4" ".give/${1}" && 
mv ".give/${1}/${4}" ".give/${1}/_AUTOMARKING" &&
echo "assignment ${1} created"
