#!/bin/dash

if test "$#" -ne 0
then
    echo "usage: give-summary"
    exit 1
fi

if ! test -e ".give"
then
    echo 'no assignments'
fi

cd .give &&
for assignment in *
do
    if ! test "$assignment" = "*"
    then
        i=0
        cd "$assignment" &&
        for zid in z[0-9]*/
        do
            if ! test "$zid" = 'z[0-9]*/'
            then
                i=$((i+1))
            fi
        done
        echo "assignment ${assignment}: submissions from ${i} students" &&
        cd '-' >/dev/null
    else
        echo "no assignments"
    fi
done 
